const data = [
  {
    name: 'Mailchimp',
    profileImage: "https://www.pngitem.com/pimgs/m/166-1667214_child-head-with-smiling-face-child-face-icon.png",
    daysSinceApplied: 1,
    tag: 'Design',
    position: 'Senior Product Designer',
    country: 'Singapore',
    totalCapacity: 50,
    appliedCapacity: 32,
  },
  {
    name: 'Dribble',
    profileImage: "https://www.pngitem.com/pimgs/m/166-1667214_child-head-with-smiling-face-child-face-icon.png",
    daysSinceApplied: 4,
    tag: 'Product',
    position: 'Junior Frontend Developer',
    country: 'Singapore',
    totalCapacity: 70,
    appliedCapacity: 60,
  },
  {
    name: 'Reddit',
    profileImage: "https://www.pngitem.com/pimgs/m/166-1667214_child-head-with-smiling-face-child-face-icon.png",
    daysSinceApplied: 2,
    tag: 'Design',
    position: 'Business Analyst',
    country: 'USA',
    totalCapacity: 100,
    appliedCapacity: 52,
  },
  {
    name: 'Ibrahim',
    profileImage: "https://www.pngitem.com/pimgs/m/166-1667214_child-head-with-smiling-face-child-face-icon.png",
    daysSinceApplied: 1,
    tag: 'Development',
    position: 'UX/UI Designer',
    country: 'Singapore',
    totalCapacity: 80,
    appliedCapacity: 32,
  },
  {
    name: 'AlRayyan',
    profileImage: "https://www.pngitem.com/pimgs/m/166-1667214_child-head-with-smiling-face-child-face-icon.png",
    daysSinceApplied: 7,
    tag: 'Design',
    position: 'Senior Backend Developer',
    country: '  Egypt',
    totalCapacity: 60,
    appliedCapacity: 55,
  },
  {
    name: 'Mohammed',
    profileImage: "https://www.pngitem.com/pimgs/m/166-1667214_child-head-with-smiling-face-child-face-icon.png",
    daysSinceApplied: 1,
    tag: 'Sales',
    position: 'Senior Product Designer',
    country: 'Brazil',
    totalCapacity: 90,
    appliedCapacity: 44,
  },
  {
    name: 'Ahmed',
    profileImage: "https://www.pngitem.com/pimgs/m/166-1667214_child-head-with-smiling-face-child-face-icon.png",
    daysSinceApplied: 3,
    tag: 'Product',
    position: 'Senior Frontend Designer',
    country: 'France',
    totalCapacity: 80,
    appliedCapacity: 60,
  },
  {
    name: 'Sarah',
    profileImage: "https://www.pngitem.com/pimgs/m/166-1667214_child-head-with-smiling-face-child-face-icon.png",
    daysSinceApplied: 1,
    tag: 'Design',
    position: 'Senior Technical Requiter',
    country: 'China',
    totalCapacity: 50,
    appliedCapacity: 40,
  },
];

module.exports = data;